from rich import print
from os import system
system("clear||cls")

print("[red underline]>Oh, thank you! Alright, first off we need to find the spear.<")
print("")
print("You ask what you would need a spear for.")
print("")
print("[red underline]>Ah, no, it's not an actual spear, it's a big weapon we made to 'contain' those monsters.<")
print("")
print("[red underline]>If my map here is right, we should find it if we head north. . . uh, do you have a compass on you?<")
print("")
print("As luck would have it, the only compass you have is on your phone, which has too low battery power.")
print("")
print("[red underline]>Ah. . . uh, that's okay. . . we can. . . we can just, uhhh. .  . oh! what if we went up this hill?<")
print("")
print("The specific hill that Lisa is pointing at appears to be covered in thorns. The climb will be perilous, if not impossible.")
print("")
print("[red underline]>Oh, perilous shmerilous. In training you have to go through three of those! not to mention the flower-men and antimatter-")
print("")
print("[red underline]*ahem* Excuse me.<")
print("")
print("[red underline]>Okay! time to go. . . up the hill.<")
print("")
print("Right before you can begin climbing the mountain, the thorns that cover it rapidly extend down and grab you.")
print("")
print("You and Lisa are dragged up the hill, and into it.")
print("")
print("As it turns out, the thorns that covered the hill were part of a larger creature, which resided underground.")
print("")
print("There is no light beneath the hill that the thorn-creature lives in.")
print("")
print("the final minutes before you lose conciousness is spent without sight, sound, or even feeling.")
print("")

print("The end!")
print("go back to page 1 to try again.")