from rich import print
from os import system
system("clear||cls")

print("You ascend up the stairs, to the light part of the lighthouse.")
print("")
print("Upon making it to the top, you you stare into the light.")
print("")
print("Not actual light, of course. The thing is broken, as if someone took a sledgehammer to it.")
print("")
print("A large section of wire also appears to be missing.")
print("")
print("Before you can examine further, however, you hear footsteps from downstairs.")
print("")
print("Someone. . . or some[italic]thing[/italic] is coming this way.")
print("")
print("Immediately, you run outside and jump off the lighthouse.")
print("")
print("As luck would have it, you land in a bush and take miniscule damage.")
print("")
print("You sprint away as fast as you can, but they are waiting for you.")
print("")
print("In an instant, you are tackled to the ground and sedated.")
print("")
print("The next time you wake up, you're in an insane asylum.")
print("")
print("")
print("The end!")
print("Go back to page 1 to try again.")