from rich import print
from os import system
system("clear||cls")

print("You stomp through the holes, mud and other ground objects and make your way to the planks.")
print("")
print("[red underline]<Oh, thank goodness. that was too close.>")
print("")
print("The voice from earlier reveals itself.")
print("")
print("[red underline]<My name is, uh... Lisa, and, um... i'm here to... uh... rescue?- Rescue you!>")
print("")
print("You may have just walked out of one trap and into another.")
print("")
print("You inquire as to >[red underline]Lisa[/red underline]<'s affiliation.")
print("")
print("[red underline]<Oh, uh.. the crypt... something... Oh yeah! The [/red underline][white on blue]Cryptid Containment Center[/white on blue]!>")
print("")
print("[red underline]<You know, the brave guys and girls who risk their lives to save the poor, innocent townsfolk from the creatures of legend!>")
print("")
print("Just pretending to understand this woman is difficult.")
print("")
print("You've never heard of this [white on blue]Cryptid Containment Center[/white on blue], and don't know much about cryptids, either.")
print("")
print("However, there doesn't seem to be many options.")
print("")
print("That monster from when you woke up is probably still chasing you,")
print("")
print("You don't know what time it is,")
print("")
print("And there's not another soul for miles.")
print("")
print("")
print("With all these facts in mind, you consider your options.")
print("")
choice = input("")