from rich import print
from os import system
system("clear||cls")

print("You try to work the terminal.")
print("")
print("However, there are so many flashing lights and strange buttons.")
print("")
print("Nothing makes sense to you.")
print("")
print("In the time you wasted trying to get the terminal to do something, a security guard arrived.")
print("")
print("You are just about to ask him for help when he tases you.")
print("")
print("The next time you wake up, you're on trial.")
print("")
print("Apparently a whole month had gone by in the time between being tased and now.")
print("")
print("You don't even know what you're being tried for.")
print("")
print("Finally, the judge says you are guilty of breaking and entering, murder, tresspassing, arson, grand theft auto, corporate espionage, sabatoge, and littering.")
print("")
print("Before you can even get a word out, you are dragged outside the courtroom and thrown in the prison bus.")
print("")
print("The world as you know it is gone, all that is left are corrupt security guards that get you in trouble for their crimes.")
print("")
print("")
print("The end!")