from rich import print
from os import system
system("clear||cls")

print("[red underline]<No, what are you doing!? I'm not lying! It's not safe there! [/red underline][bold red underline]Come back! Please!>[/bold red underline]")
print("")
print("The voice cannot be trusted.")
print("")
print("You dash away as far as your legs can take you. . .")
print("")
print(". . .Which isn't far, as after 5 minutes, you fall into a ravine.")
print("")
print("This ravine just so happens to have no way out.")
print("")
print("You have evaded one horror of the forest, only to fall right into another.")
print("")
print("[bold black]A week later, you - or what is left of you - are found by some hikers and taken back with them.")
print("")
print("[bold black]Now your remains sit in a museum, in a section detailing the 'mouth of the devil', which has claimed the lives of many wanderers of the forest.")
print("")
print("[bold black]The end!")