from rich import print
from os import system
system("clear||cls")

print("the power button for the 'radio' was difficult to find, and even more difficult to press.")
print("")
print("even then, it takes at least 5 minutes to turn on.")
print("")
print("Just when you're about to fiddle with it's knobs, you hear a voice coming from it.")
print("")
print("[bold green]<Michael? Michael!? Are you there? Michael?>")
print("")
print("You do not recognize the voice.")
print("")
print("[bold blue underline]<Michael, this is headquarters. Extraction is not coming. We've been backstabbed. The whole organization is under assault. Michael, are you there?>")
print("")
print("The people on the other side are searching for a 'Michael'.")
print("")
print("You reply that there is no 'Michael' nearby, let alone another human.")
print("")
print("[bold green]<What!? Then- Then who is this!?>")
print("")
print("[bold blue underline]<Sir, i'll have you know you are in possession of->")
print("")
print("You cut off the voice and demand answers to a way out of the forest.")
print("")
print("The low-pitched voice responds,")
print("")
print("[bold blue underline]<Negative. All entrances are sealed and surrounded. Anyone. . .or any[italic]thing[/italic] that attempts to leave the forest will be destroyed where it stands.")
print("")
print("[bold blue underline]<However. . .Where did you find that communicator?>")
print("")
print("You say you found it in the lighthouse.")
print("")
print("[bold blue underline]<I figured. There's a bomb shelter underneath the floor there. if you hide in it, you should be safe until tomorrow.")
print("")
print("The voices walk you through how to locate it.")
print("")
print("You locate it after far too long, and descend down.")
print("")
print("[bold blue underline]<I must also ask you tell not a soul of what you saw this night.>")
print("")
print("[bold green]<Yeah, can't have the normal folks finding out about this. . .>")
print("")
print("If you make an anonymous tip to the paper, they can't trace it back to you, so you wonder if you [italic]should[/italic] comply with such a request.")
print("")
print("but no matter. you close the door to the shelter and wait.")
print("")
print("####################################################################################################")
print("")
print("Days go buy, yet no one has come to rescue you.")
print("")
print("There's no way to tell if the creature is still there, either.")
print("")
print("Food is scarce as well, as there is but one tiny sandwich lying on the floor.")
print("")
print("The hunger becomes too much, and you take a bite.")
print("")
print("It's the most disgusting sandwich you've ever eaten.")
print("")
print("Worse yet, not even 5 minutes after you took a bite, you feel something wrong.")
print("")
print("By the time you think to throw it up, you're collapsing on the ground.")
print("")
print("As you struggle for conciousness, you can vaguely hear something outside.")
print("")
print("but it's of no concern to you now. All you desire is to wake up tomorrow.")

print("The end!")